### ISSUE TITLE
[bug] incorrect despawn_sec value

### ISSUE THREAD

**Issue by clburlison** [versx/DataParser#4]
Spawn points have an incorrect `despawn_sec` value saved to the database. 

After comparing DataParser to GFC the only real difference I can find is you're calling the [getCurrentTimestamp()](https://github.com/versx/GoFestController/blob/4396df19e4d3c562a958b896054cef9a74d69710/src/utilities/utils.js#L3-L6) method over in GFC. In DataParser model/pokemon.js there are a bunch of `new Date().getTime() / 1000` creations that aren't wrapped inside of `Math.round()` but that alone doesn't resolve the issue.

Either way comparing Dataparser spawnpoint table to RDM table results in 100% different values for me. Will try to look again this weekend...

**Comment by versx** [comment]
Thanks for testing, was with the webhooks branch or master?

**Comment by clburlison** [comment]
both branches had the same results.

**Comment by versx** [comment]
Oof, thanks I'll look into it some more.

**Comment by versx** [comment]
I think I fixed this in the `redis` branch if you want to give it another test.

**Comment by clburlison** [comment]
With PR #11 and #12 going to say this is finally resolved. Thanks @bschultz and @versx
